/* dtool_config.h.  Generated automatically by makepanda.py */
#define HAVE_FMODEX 1
#undef IS_FREEBSD
#undef MESA_MGL
#define HAVE_VRPN 1
#define HAVE_RTTI 1
#define PHAVE_IO_H 1
#undef PHAVE_SYS_MALLOC_H
#undef PHAVE_DIRENT_H
#define DO_PSTATS 1
#undef MAYA_PRE_5_0
#undef PROTOTYPE_GLOBAL_ARGV
#define HAVE_DX9 1
#define HAVE_DX8 1
#undef HAVE_DINKUM
#define GLOBAL_ARGV __argv
#undef HAVE_OPEN_MASK
#undef HAVE_P3D_PLUGIN
#undef PHAVE_ALLOCA_H
#define HAVE_TYPENAME 1
#undef HAVE_GLX
#undef PHAVE_GLOB_H
#undef PYTHON_FRAMEWORK
#define GLOBAL_ARGC __argc
#define HAVE_FFTW 1
#define HAVE_ODE 1
#undef PHAVE_STDLIB_H
#define HAVE_SOFTIMAGE_PIC 1
#undef PHAVE_GETOPT_H
#define DEFAULT_PATHSEP ";"
#undef HAVE_XCURSOR
#define HAVE_WCHAR_T 1
#undef PHAVE_LIMITS_H
#undef HAVE_PROC_SELF_CMDLINE
#undef PHAVE_LOCALE_H
#undef LINK_IN_GL
#define HAVE_CG 1
#undef PHAVE_UTIME_H
#undef HAVE_PROC_SELF_MAPS
#define USE_DELETED_CHAIN 1
#define COMPILE_IN_DEFAULT_FONT 1
#define HAVE_IOS_BINARY 1
#define HAVE_ZLIB 1
#undef HAVE_CHROMIUM
#define HAVE_NVIDIACG 1
#undef HAVE_SGIGL
#undef HAVE_EIGEN
#define HAVE_FREETYPE 1
#define PHAVE_IOSTREAM 1
#define HAVE_CGGL 1
#define HAVE_FFMPEG 1
#undef HAVE_MESA
#define PHAVE_NEW 1
#define HAVE_FCOLLADA 1
#define STATIC_INIT_GETENV 1
#define HAVE_WGL 1
#define HAVE_ARTOOLKIT 1
#undef PHAVE_UCONTEXT_H
#define PHAVE_JPEGINT_H 1
#define HAVE_MAYA 1
#define EXPORT_TEMPLATES yes
#define HAVE_ROCKET_DEBUGGER 1
#define PHAVE_SSTREAM 1
#undef HAVE_GETOPT_LONG_ONLY
#define HAVE_JPEG 1
#undef PHAVE_UNISTD_H
#undef PHAVE_SYS_TIME_H
#define HAVE_SWSCALE 1
#define PHAVE_MINMAX_H 1
#undef HAVE_SPEEDTREE
#undef SIMPLE_THREADS
#define HAVE_NAMESPACE 1
#define HAVE_OPENSSL 1
#define HAVE_OPENCV 1
#undef HAVE_OPENAL_FRAMEWORK
#undef PHAVE_LINUX_INPUT_H
#define HAVE_GLOBAL_ARGV 1
#define NOTIFY_DEBUG 1
#define SIMPLE_STRUCT_POINTERS 1
#define HAVE_IMG 1
#define HAVE_PNG 1
#define HAVE_PNM 1
#define PHAVE_MALLOC_H 1
#undef HAVE_PROC_SELF_EXE
#undef GLOBAL_OPERATOR_NEW_EXCEPTIONS
#undef GETTIMEOFDAY_ONE_PARAM
#define HAVE_DIRECTCAM 1
#define DO_MEMORY_USAGE 1
#undef HAVE_GETOPT
#undef HAVE_PROC_SELF_ENVIRON
#define SUPPORT_IMMEDIATE_MODE 1
#define USE_PANDAFILESTREAM 1
#undef TRACK_IN_INTERPRETER
#define REPORT_OPENSSL_ERRORS 1
#define OS_SIMPLE_THREADS 1
#define HAVE_TGA 1
#undef WORDS_BIGENDIAN
#undef HAVE_XF86DGA
#define DO_PIPELINING 1
#define PRC_SAVE_DESCRIPTIONS 1
#undef STDFLOAT_DOUBLE
#undef HAVE_EGL
#undef HAVE_STL_HASH
#undef IS_LINUX
#define HAVE_EGG 1
#define HAVE_GL 1
#undef HAVE_XRANDR
#undef HAVE_GLES2
#undef USE_GENERIC_DXERR_LIBRARY
#define HAVE_OPENAL 1
#undef HAVE_SOFTIMAGE
#define HAVE_SQUISH 1
#undef LINK_IN_PHYSICS
#define HAVE_TIFF 1
#define HAVE_NET 1
#define DO_DCAST 1
#undef USE_DEBUG_PYTHON
#undef SSL_097
#define HAVE_WSTRING 1
#undef HAVE_PROC_CURPROC_FILE
#define HAVE_SGI_RGB 1
#undef HAVE_VIDEO4LINUX
#define HAVE_BMP 1
#undef HAVE_GETTIMEOFDAY
#undef HAVE_GLES
#define HAVE_STREAMSIZE 1
#undef HAVE_WIN_TOUCHINPUT
#define HAVE_CGDX9 1
#define LINMATH_ALIGN 1
#undef IOCTL_TERMINAL_WIDTH
#undef DEBUG_THREADS
#define HAVE_AUDIO 1
#undef IS_OSX
#undef PHAVE_STDINT_H
//#define HAVE_PYTHON 1
#define PHAVE_SYS_TYPES_H 1
#define HAVE_ROCKET_PYTHON 1
#define DO_COLLISION_RECORDING 1
#undef HAVE_POSIX_THREADS
#undef HAVE_PROC_CURPROC_MAP
#undef HAVE_X11
#undef PHAVE_STRING_H
#define HAVE_IOS_TYPEDEFS 1
#undef PHAVE_SYS_SOUNDCARD_H
#define HAVE_THREADS 1
